dist: xenial
language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
cache: bundler
addons:
  apt:
    packages:
    - libsodium-dev
before_install:
  - gem update --system && gem install --no-document bundler
script: bundle exec rake travis
notifications:
  slack:
    secure: V/6a8KFe067uukrbCJA2R1HPO4xy0YSQ1pwmHVRi5StX+yl+lYsWWJdjdBdT0j3iJBYyPRqU4bQYck+OloxtELnrHCX+OkodxcxW8W/ACc914iIf0FyY9pnusK7ck2awmt4Iuf94YPgi0XTm1aCcm+f0yU7wiIVFpftoXSk1EDY=
