dist: xenial
language: ruby
rvm:
- 2.5
- 2.6
- 2.7
cache: bundler
addons:
  apt:
    packages:
    - libsodium-dev
before_install:
- gem install --no-document bundler
script: bundle exec rake travis
notifications:
  slack:
    secure: bDnL49rSqA62Q95NAw9guu9+5YVGMhzRpHohpuI6om72VU0kkEErpPf92H1CadJKnD39YtIAkm/uOdZWIfqTbAECs2XrVci83OHFW25xBYMwGbUF5RgRja+QS+sg6lMFReDkciB9iaiT0UmcA/IbkftGE7FKlldfPYofLID+974=
